// Generated by scripts/generate-authoring-metadata.mjs. Do not edit.
export const componentImplementationSourceHash =
  "3b29044caeef3f95a0f564c8a402efb64dfac2f09add90d6301d62ce7574a7b7";
export const componentImplementationByName = {
  MdcColumn: {
    componentName: "MdcColumn",
    props: {
      size: {
        required: false,
        types: ["string", "object"],
        default: "md",
        options: ["sm", "md", "lg"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcInfo: {
    componentName: "MdcInfo",
    props: {
      title: {
        required: false,
        types: ["string"],
      },
      icon: {
        required: false,
        types: ["string"],
      },
      appearance: {
        required: false,
        types: ["string"],
        options: ["quiet", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcLayout: {
    componentName: "MdcLayout",
    props: {
      type: {
        required: false,
        types: ["string", "object"],
        default: "default",
        options: ["default", "card", "border", "border-dashed", "outline", "outline-dashed"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
} as const;
