// Generated by scripts/generate-authoring-metadata.mjs. Do not edit.
export const componentImplementationSourceHash =
  "5ad02959668ce9a62b13feec24299f00b0c152cc788e6772e01492f242a5b88c";
export const componentImplementationByName = {
  MdcAside: {
    componentName: "MdcAside",
    props: {
      label: {
        required: false,
        types: ["string"],
      },
      appearance: {
        required: false,
        types: ["string"],
        options: ["quiet", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcFlow: {
    componentName: "MdcFlow",
    props: {
      width: {
        required: false,
        types: ["string"],
        default: "reading",
        options: ["reading", "wide"],
      },
      surface: {
        required: false,
        types: ["string"],
        default: "default",
        options: ["default", "muted", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcFigure: {
    componentName: "MdcFigure",
    props: {
      src: {
        required: false,
        types: ["string"],
      },
      alt: {
        required: false,
        types: ["string"],
      },
      caption: {
        required: false,
        types: ["string"],
      },
      width: {
        required: false,
        types: ["string", "number"],
      },
      height: {
        required: false,
        types: ["string", "number"],
      },
      bleed: {
        required: false,
        types: ["boolean", "string"],
      },
      aspect: {
        required: false,
        types: ["string"],
        options: ["auto", "video", "wide", "square", "portrait"],
      },
      fit: {
        required: false,
        types: ["string"],
        options: ["cover", "contain"],
      },
      placement: {
        required: false,
        types: ["string"],
        options: ["inline", "start", "end"],
      },
      frame: {
        required: false,
        types: ["string"],
        options: ["default", "none"],
      },
      focus: {
        required: false,
        types: ["string"],
        options: ["center", "top", "bottom", "left", "right"],
      },
      zoom: {
        required: false,
        types: ["boolean", "string"],
        default: "auto",
      },
      class: {
        required: false,
        types: ["complex"],
      },
      appearance: {
        required: false,
        types: ["string"],
        options: ["quiet", "tint"],
      },
    },
    slots: ["default"],
  },
  MdcError: {
    componentName: "MdcError",
    props: {
      title: {
        required: false,
        types: ["string"],
      },
      icon: {
        required: false,
        types: ["string"],
      },
      appearance: {
        required: false,
        types: ["string"],
        options: ["quiet", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcExcerpt: {
    componentName: "MdcExcerpt",
    props: {
      label: {
        required: false,
        types: ["string"],
      },
      source: {
        required: false,
        types: ["string"],
      },
      size: {
        required: false,
        types: ["string"],
        options: ["body", "display"],
      },
      appearance: {
        required: false,
        types: ["string"],
        options: ["quiet", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcIdea: {
    componentName: "MdcIdea",
    props: {
      title: {
        required: false,
        types: ["string"],
      },
      icon: {
        required: false,
        types: ["string"],
      },
      appearance: {
        required: false,
        types: ["string"],
        options: ["quiet", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcNote: {
    componentName: "MdcNote",
    props: {
      title: {
        required: false,
        types: ["string"],
      },
      icon: {
        required: false,
        types: ["string"],
      },
      appearance: {
        required: false,
        types: ["string"],
        options: ["quiet", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcSuccess: {
    componentName: "MdcSuccess",
    props: {
      title: {
        required: false,
        types: ["string"],
      },
      icon: {
        required: false,
        types: ["string"],
      },
      appearance: {
        required: false,
        types: ["string"],
        options: ["quiet", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcWarning: {
    componentName: "MdcWarning",
    props: {
      title: {
        required: false,
        types: ["string"],
      },
      icon: {
        required: false,
        types: ["string"],
      },
      appearance: {
        required: false,
        types: ["string"],
        options: ["quiet", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcColumn: {
    componentName: "MdcColumn",
    props: {
      size: {
        required: false,
        types: ["string", "object"],
        default: "md",
        options: ["xs", "sm", "md", "lg", "xl"],
      },
      align: {
        required: false,
        types: ["string"],
        options: ["start", "center", "end"],
      },
      media: {
        required: false,
        types: ["string"],
        default: "natural",
        options: ["natural", "cover", "contain"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcInfo: {
    componentName: "MdcInfo",
    props: {
      title: {
        required: false,
        types: ["string"],
      },
      icon: {
        required: false,
        types: ["string"],
      },
      appearance: {
        required: false,
        types: ["string"],
        options: ["quiet", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
  MdcLayout: {
    componentName: "MdcLayout",
    props: {
      type: {
        required: false,
        types: ["string", "object"],
        default: "default",
        options: ["default", "card", "border", "border-dashed", "outline", "outline-dashed"],
      },
      align: {
        required: false,
        types: ["string"],
        default: "start",
        options: ["start", "center", "end"],
      },
      gap: {
        required: false,
        types: ["string"],
        default: "md",
        options: ["none", "sm", "md", "lg"],
      },
      stack: {
        required: false,
        types: ["string"],
        default: "md",
        options: ["sm", "md", "lg"],
      },
      surface: {
        required: false,
        types: ["string"],
        default: "default",
        options: ["default", "muted", "tint"],
      },
      class: {
        required: false,
        types: ["complex"],
      },
    },
    slots: ["default"],
  },
} as const;
