packages:
  - layer
  - playground

autoInstallPeers: false

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  vue-demi: true

overrides:
  vite: "catalog:"
  vitest: "catalog:"
  "@lupinum/ginko-content": 0.3.6

peerDependencyRules:
  allowedVersions:
    vite: "*"
    vitest: "*"
  allowAny:
    - vite
    - vitest
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vitest: 4.1.10
  vite-plus: 0.2.8
