export const contentComponentTags = {
  accordion: "MdcAccordion",
  "accordion-item": "MdcAccordionItem",
  alert: "MdcAlert",
  aside: "MdcAside",
  callout: "MdcCallout",
  card: "MdcCard",
  "card-group": "MdcCardGroup",
  center: "MdcCenter",
  "code-group": "MdcCodeGroup",
  column: "MdcColumn",
  danger: "MdcError",
  "doc-img": "MdcDocImg",
  dropcap: "MdcDropcap",
  error: "MdcError",
  field: "MdcField",
  "field-group": "MdcFieldGroup",
  figure: "MdcFigure",
  idea: "MdcIdea",
  img: "ProseImg",
  info: "MdcInfo",
  layout: "MdcLayout",
  note: "MdcNote",
  passage: "MdcPassage",
  quiz: "MdcQuiz",
  "quiz-option": "MdcQuizOption",
  "quiz-question": "MdcQuizQuestion",
  "read-more": "MdcReadMore",
  "read-more-group": "MdcReadMoreGroup",
  shortcut: "MdcShortcut",
  step: "MdcStep",
  steps: "MdcSteps",
  success: "MdcSuccess",
  tab: "MdcTab",
  tabs: "MdcTabs",
  timeline: "MdcTimeline",
  "timeline-item": "MdcTimelineItem",
  warn: "MdcWarning",
  warning: "MdcWarning",
} as const;

export const contentComponentNames = Array.from(new Set(Object.values(contentComponentTags)));

export type ContentComponentTag = keyof typeof contentComponentTags;
export type ContentComponentName = (typeof contentComponentTags)[ContentComponentTag];
